services:
    server:
        build: ./server
        ports: 
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    client:
        build: ./client
        volumes:
        - ./client/src:/app/src
        ports:
        - "8081:80"
        environment:
        - CHOKIDAR_USEPOLLING=true
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db